{"uuid": "51f077fc-5ee3-45cc-8cdf-619585e530f0", "children": ["6ce223ff-9089-418f-94cd-7cc830c6bf24"], "befores": [{"name": "setup", "status": "failed", "statusDetails": {"message": "AssertionError: User icon is not presented, probably unauthorised user\n", "trace": "  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 890, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\user\\Desktop\\Ыгоры\\Для собесов\\pythonProject1\\test_product_page.py\", line 90, in setup\n    login_page.should_be_authorized_user()\n  File \"C:\\Users\\user\\Desktop\\Ыгоры\\Для собесов\\pythonProject1\\pages\\base_page.py\", line 57, in should_be_authorized_user\n    assert self.is_element_present(\n"}, "start": 1683541557734, "stop": 1683541573215}], "start": 1683541557734, "stop": 1683541573281}