{"uuid": "12da2959-2f74-43fa-ac5c-da1a4c647c9c", "children": ["2d315425-4ac3-49d0-a172-ecf79216bd16"], "befores": [{"name": "browser", "status": "passed", "start": 1683537779649, "stop": 1683537780794}], "afters": [{"name": "browser::0", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\user\\PycharmProjects\\pythonProject1\\conftest.py\", line 18, in browser\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 233, in quit\n    super().quit()\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 564, in quit\n    self.execute(Command.QUIT)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 433, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 344, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 366, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\request.py\", line 74, in request\n    return self.request_encode_url(\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\request.py\", line 96, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 813, in urlopen\n    return self.urlopen(\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 813, in urlopen\n    return self.urlopen(\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 703, in urlopen\n    httplib_response = self._make_request(\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connectionpool.py\", line 398, in _make_request\n    conn.request(method, url, **httplib_request_kw)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connection.py\", line 239, in request\n    super(HTTPConnection, self).request(method, url, body=body, headers=headers)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 1252, in request\n    self._send_request(method, url, body, headers, encode_chunked)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 1298, in _send_request\n    self.endheaders(body, encode_chunked=encode_chunked)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 1247, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 1007, in _send_output\n    self.send(msg)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python38\\lib\\http\\client.py\", line 947, in send\n    self.connect()\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connection.py\", line 205, in connect\n    conn = self._new_conn()\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\connection.py\", line 174, in _new_conn\n    conn = connection.create_connection(\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\urllib3\\util\\connection.py\", line 85, in create_connection\n    sock.connect(sa)\n"}, "start": 1683538728056, "stop": 1683538744421}], "start": 1683537779649, "stop": 1683538744421}